### ISSUE TITLE
Usando AJAX request para enviar el formulario [CLIENTE SDK]

### ISSUE THREAD

**Issue by AAhrit** [mercadopago/px-nodejs#73]
Hola, hay alguna posibilidad de enviar el formulario del lado del cliente a los servidores mediante ajax? es que estoy haciendo una aplicacion web de una sola pagina y no quisiera refrescar la pagina para enviar esos datos de la tarjeta del usuario.

**Comment by arielfr** [comment]
Existen implementaciones de MercadoPago client side. Podes usar una que es la de redirect, que pones un botón de pago y este lleva a MercadoPago y una vez realizado el pago vuelve a tu página. Sino podes implementar un modal.

Igualmente, te cuento, que esta es una implementación de la API de MercadoPago, podes usarla para hacer pagos del lado server o hacer un checkout customizado y hacer todo el flujo en tu página.

Te cuento que si vas a implementar Client + Server, no podes pasar los datos de tarjeta al servidor, tenes que usar la SDK de Javascript para tokenizar la tarjeta y luego enviar ese Token a tu server para realizar el pago, de lo contrario estarías rompiendo las normas PCI de seguridad.

Te recomiendo un botón de pago con redirect para una implementación fácil y rapida.

Cualquier cosa, te invito a ver el sitio de desarrolladores:

[https://www.mercadopago.com.ar/developers/](Developers Site)

**Comment by AAhrit** [comment]
es que el boton es muy limitativo, y si estoy utilizando el client sdk para tokenizar solo que no quisiera que la pagina se refresque cuando envie el token al servidor ya que para eso voy a utilizar fetch

**Comment by arielfr** [comment]
Si, podes enviar por AJAX el token a tu servidor tranquilamente.
