### ISSUE TITLE
Sandbox no funciona

### ISSUE THREAD

**Issue by lainz** [mercadopago/px-nodejs#74]
Hola, con el siguiente código puedo llegar a la página de pago, pero cuando intento realizar el pago me rechazan la tarjeta, y estoy usando la que ustedes proveen en el sitio sandbox. Intenté cambiando el mail por uno real pero llego siempre al mismo error (imagen adjunta). Tengo configurado correctamente client id y client secret, en este caso los removí para mostrarles el código.

```
'use strict';

export function pagos(req, res) {
  var MP = require("mercadopago");
  // client id, client secret
  // https://www.mercadopago.com/mla/herramientas/aplicaciones
  var mp = new MP("", "");
  var preference = {};

  var item = {
    id: '0001',
    title: 'Pago mensual de POSBerry',
    quantity: 1,
    currency_id: 'ARS',
    unit_price: 400
  }

  var payer = {
    email: "test@test.com"
  }

  preference.items = [item]
  preference.payer = payer

  mp.createPreference(preference).then(function (data) {
    console.log(data)
     res.send(`
     <!DOCTYPE html>
     <html>
         <head>
             <title>Pagar</title>
         </head>
         <body>
             <a href="${data.response.sandbox_init_point}">Pagar</a>
         </body>
     </html>
     `);
   }).catch(function (error) {
    res.send(`
    <!DOCTYPE html>
    <html>
        <head>
            <title>Pagar</title>
        </head>
        <body>
            Error: no se procesó el pago.
        </body>
    </html>
    `);
   });
}
```

![sandbox](https://user-images.githubusercontent.com/4131395/31320445-13c6dd8a-ac4b-11e7-9267-597d2ef44983.png)

Me interesa implementar primero el pago y recibir la notificación IPN, esto es lo que tengo hasta ahora, pero nunca llegué a testearlo porque no puedo efectuar el pago en modo sandbox. De todos modos he configurado la URL y recibo la notificacion al darla de alta, pero necesito probar actualmente con una compra.

```
'use strict';
// configurar URL notificacion
// https://www.mercadopago.com.ar/ipn-notifications

export function notificaciones(req, res) {
    var MP = require("mercadopago");
    // client id, client secret
    // https://www.mercadopago.com/mla/herramientas/aplicaciones
    var mp = new MP("", "");

    mp.getPayment(req.body.id).then(
        function success(data) {
            console.log(JSON.stringify(data, null, 4));
        },
        function error(err) {
            console.log(err);
        }
    );
    res.sendStatus(200);
}
```

No pude convertir el código a la nueva versión beta... La documentación no tiene un ejemplo completo como modelo a seguir para el checkout básico, o al menos yo no pude.

**Comment by arielfr** [comment]
Buenas, ya te respondí aca: https://github.com/mercadopago/sdk-nodejs/issues/30
